"""add media_avaliacoes

Revision ID: e2313c722c5e
Revises: 001
Create Date: 2026-04-13 17:22:15.396403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2313c722c5e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('produtos', sa.Column('media_avaliacoes', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('total_avaliacoes', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'total_avaliacoes')
    op.drop_column('produtos', 'media_avaliacoes')
    # ### end Alembic commands ###
